### ISSUE TITLE
EnvMap Skybox Visor reflection textures included in distribution

### ISSUE THREAD

**Issue by Poodmund** [RangeMachine/TextureReplacer#1]
The small EnvMap textures that display the reflection of the Skybox in the visor have been included in the v2.5.1 release, featuring textures from some Skybox.

This inclusion causes issues when users are trying to install Skyboxes via CKAN as it will not allow the Skybox the user is trying to install to overwrite the bundled EnvMap textures.

Could these textures please be removed from the distribution as to not cause further issues, as per the v2.4.16 and previous releases?

Let me know what you think. :D

**Comment by RangeMachine** [comment]
Yes, of course, i will delete it.

**Comment by RangeMachine** [comment]
Done. I deleted all EnvMap textures from releases.

**Comment by Poodmund** [comment]
RangeMachine, would it be too much of an issue to push the updated build to a new release to resolve this issue?

I am receiving messages about additional Skyboxes not working when downloading via CKAN quite frequently so it seems problems are still being had without users realising the issue at hand.

**Comment by RangeMachine** [comment]
Done. https://github.com/RangeMachine/TextureReplacer/releases/tag/v2.5.2

**Comment by Poodmund** [comment]
My hero! :+1:
